### ISSUE TITLE
Logiciel pour le fichier XML

### ISSUE THREAD

**Issue by Poussinou** [toulibre/cdl-companion-android#2]
Bonjour,
I will speak in French here since you're from Toulouse, but ask me to translate if needed!

Juste une petite question, je vois dans le code source que l'application lit les informations à afficher dans un fichier XML dédié à ce type d'évènement (nom de l'intervenant, horaire...). J'aurais aimé savoir si vous utilisiez un logiciel en particulier pour cela ou pas, et si oui lequel exactement?

Merci d'avance

**Comment by lporcheron** [comment]
Bonjour Poussinou,

Notre logiciel de gestion de conférence pour le Capitole du Libre génère ce fichier XML. En 2014 et 2015 nous avons utilisé Symposion. Depuis 2016, nous utilisons un logiciel que nous avons développé PonyConf. Il est situé aussi sur le github de Toulibre. C'est Open Source :)

Lionel

**Comment by bishiboosh** [comment]
Et pour rajouter : le parsing du XML est fait ensuite en natif dans l'app (même si j'ai pour projet de me mettre à utiliser une vraie lib à la place)

**Comment by Poussinou** [comment]
Merci beaucoup de l'information, je vais aller voir ça avec plaisir :)
Je vais aller étudier le parsing du XML aussi du coup.
J’espère déployer une nouvelle version de cette application pour les congrès du mouvement des Junior-Entreprises française, et écrire de la documentation pour que n'importe qui puisse construire sa propre version pour l’événement de son choix, d'où la recherche du logiciel permettant de créer le fichier XML.

Merci encore

**Comment by bishiboosh** [comment]
@Poussinou : très bonne initiative, cela dit le code de l'app est un peu vieux, et j'espère pouvoir le refactorer quand j'en aurais le temps pour faire une meilleure base :)
